;platformio.ini

; [env:nrf52840_MASTER]
; platform      = https://github.com/Seeed-Studio/platform-seeedboards.git
; board         = seeed-xiao-afruitnrf52-nrf52840
; framework     = arduino
; upload_port   = /dev/cu.usbmodem14201
; monitor_port  = /dev/cu.usbmodem14201
; monitor_speed = 115200
; build_flags   =
;     -D TARGET_NRF52840
;     -D ROLE_MASTER
;     -D SERIAL_BAUD=${env.monitor_speed}
;     -DCFG_TUD_ENABLED=1
;     -DCFG_TUD_CDC=1
; build_src_filter =
;     -<*>
;     +<master/main.cpp>
; monitor_dtr = 1

; [env:nrf52840_SLAVE1]
; platform      = https://github.com/Seeed-Studio/platform-seeedboards.git
; board         = seeed-xiao-afruitnrf52-nrf52840
; framework     = arduino
; upload_port   = /dev/cu.usbmodem14101
; monitor_port  = /dev/cu.usbmodem14101
; monitor_speed = 115200
; build_flags   =
;     -D TARGET_NRF52840
;     -D ROLE_SLAVE1
;     -DCFG_TUD_ENABLED=1
;     -DCFG_TUD_CDC=1
; build_src_filter =
;     -<*>
;     +<slave1/main.cpp>
; monitor_dtr = 1

[env:S3_MASTER]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
upload_port = /dev/cu.usbmodem14201
monitor_port = /dev/cu.usbmodem14201
monitor_speed = 115200
build_flags =
    -I include
    -D TARGET_ESP32S3
    -D ROLE_MASTER
    -D SERIAL_BAUD=${env.monitor_speed}
build_src_filter =
    -<*>
    +<master/main.cpp>
monitor_dtr = 1

[env:S3_SLAVE1]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
upload_port = /dev/cu.usbmodem14101
monitor_port = /dev/cu.usbmodem14101
monitor_speed = 115200
build_flags =
    -I include
    -D TARGET_ESP32S3
    -D ROLE_SLAVE1
    -D SERIAL_BAUD=${env.monitor_speed}
build_src_filter =
    -<*>
    +<slave1/main.cpp>
monitor_dtr = 1