[env:xiao_nrf52840]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
upload_port = /dev/cu.usbmodem14201
monitor_port = /dev/cu.usbmodem14201
monitor_speed = 115200
build_flags =
    -DnRF52_SERIES
    -DSERIAL_BAUD=${env.monitor_speed}


[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
upload_port = /dev/cu.usbmodem14201
monitor_port = /dev/cu.usbmodem14201
monitor_speed = 115200
build_flags =
    -DSERIAL_BAUD=${env.monitor_speed}