; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; XIAO ESP32S3 Docs
; https://docs.platformio.org/en/latest/boards/espressif32/seeed_xiao_esp32s3.html#board-espressif32-seeed-xiao-esp32s3

[platformio]
; Default environments, every node will be listed here
default_envs = S3_MASTER, S3_SLAVE1

; Load any local overrides (e.g., upload_port, monitor_port) from pio.local.ini
extra_configs = platformio_override.ini ;pio.*.ini

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_flags =
  -I include

[xiao_esp32s3]
monitor_speed = 115200

; ---- RS485 S3 MASTER ----
[env:S3_MASTER]
monitor_speed = ${xiao_esp32s3.monitor_speed}
build_flags =
  -D ROLE_MASTER
  -D THIS_ADDR=0x00
build_src_filter = 
    -<*>
    +<master/main.cpp>

; ---- RS485 S3 SLAVE1 ----
[env:S3_SLAVE1]
monitor_speed = ${xiao_esp32s3.monitor_speed}
build_flags = 
  -D ROLE_SLAVE
  -D THIS_ADDR=0x01
  -D FEATURE_LED=1
  -D FEATURE_LOC=1
build_src_filter = 
	-<*>
	+<slave1/main.cpp>
